version: '3'
services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret          

    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        depends_on:
            - db
        links:
            - db
        restart: always

    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        depends_on:
            - db
            - app
        ports:
            - "80:8080"
        links:
            - app
        restart: always