version: '3'
services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret          

    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "80:3000"
        restart: always
