version: '3'
services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        restart: always
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "5000:5000"
        restart: always
